### ISSUE TITLE
Compatibilitat amb linux

### ISSUE THREAD

**Issue by sinuso** [gerardcl/renfe-cli#191] opened 2024-01-31 19:03 UTC
Seria genial poder gaudir d'aquesta aplicació a també linux.

**Comment by gerardcl** [comment] 2024-02-02 07:28
Hola @sinuso , can you provide some screenshots or logs from what error(s) you get? thanks!

**Comment by sinuso** [comment] 2024-02-02 07:55
> Hola @sinuso , can you provide some screenshots or logs from what error(s) you get? thanks! Please, follow the issue creation templates, that helps shaping better issue reporting to the project, thanks!

In short, the application executes .exe files.
When I have a moment and I'm at home I'll take screenshots.

**Comment by sinuso** [comment] 2024-02-02 10:58
"/home/test/.local/bin/renfe-cli" makes a call to "sys.argv[0] = re.sub(r'(-script\.pyw|\**.exe**)?$', '' , sys.argv[0])"

This is what it returns when I make a query.

```
test@localhost:~$ renfe-cli -f Barc -t Mad -d 2
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-2
Searching timetable for date: 2024-2-2
loading headless chrome browser
thread '<unnamed>' panicked at src/timetable.rs:72:6:
called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugg                                                                                       ing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/test/.local/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: There are no available ports bet ween 8000 and 9000 for debugging
```

Contents of the file "/home/test/.local/bin/renfe-cli"

```
#!/usr/bin/python3.11
# -*- coding: utf-8 -*-
import re
import sys
from renfe_cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

**Comment by gerardcl** [comment] 2024-02-02 17:48
Hi @sinuso, thanks for the input!
indeed, can you try upgrading the CLI to the latest 4.2.1 renfe-cli version? I believe @henninggross fixed your issue based on the error reported by your logs! 
let me know! thanks!

**Comment by sinuso** [comment] 2024-02-02 18:38
> Hi @sinuso, thanks for the input! indeed, can you try upgrading the CLI to the latest 4.2.1 renfe-cli version? I believe @henninggross fixed your issue (here #188) based on the error reported in your logs! let me know! thanks!



I have updated but I still get the same error.

```
test@localhost:~$ pip install renfe-cli
Defaulting to user installation because normal site-packages is not writeable
Collecting renfe-cli
  Downloading renfe_cli-4.2.1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.8 kB)
Downloading renfe_cli-4.2.1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.1/6.1 MB 6.5 MB/s eta 0:00:00
Installing collected packages: renfe-cli
Successfully installed renfe-cli-4.2.1
```


```
test@localhost:~$ renfe-cli -f Barc -t Mad -d 2
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-02
Searching timetable for date: 2024-2-02
loading headless chrome browser
thread '<unnamed>' panicked at src/timetable.rs:86:6:
called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/test/.local/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
```

**Comment by sinuso** [comment] 2024-02-02 18:50
And this error is from a Windows environment.

```
C:\Users\Test> renfe-cli -f Barc -t Mad -d 2
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-02
Searching timetable for date: 2024-2-02
loading headless chrome browser
navigating to renfe timetable search page
thread '<unnamed>' panicked at src\timetable.rs:95:10:
called `Result::unwrap()` on an `Err` value: The event waited for never came
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Test\AppData\Local\Programs\Python\Python312\Scripts\renfe-cli.exe\__main__.py", line 7, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: The event waited for never came
```

**Comment by gerardcl** [comment] 2024-02-03 07:15
hi @sinuso , can you try without adding specific day (without -d flag) and also report the logs? we believe this might be due to the behaviour of the day input form in the renfe site which is really crazy. 
Also, if that still fails, could you also increase the default (2seconds) to 5 or 10? thanks!

**Comment by sinuso** [comment] 2024-02-03 10:32
@gerardcl Hi, I have done the test without -d flag and I still have the same errors.
What do you mean by increasing the seconds and how do I do it?

**Error in Linux**

```
test@localhost:~$ renfe-cli -f Barc -t Mad
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-03
Searching timetable for date: 2024-2-03
loading headless chrome browser
thread '<unnamed>' panicked at src/timetable.rs:86:6:
called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/test/.local/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
```

**Error in Windows:**

```
C:\Users\Test> renfe-cli -f Barc -t Mad
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-03
Searching timetable for date: 2024-2-03
loading headless chrome browser
navigating to renfe timetable search page
thread '<unnamed>' panicked at src\timetable.rs:95:10:
called `Result::unwrap()` on an `Err` value: The event waited for never came
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Test\AppData\Local\Programs\Python\Python312\Scripts\renfe-cli.exe\__main__.py", line 7, in <module>
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: The event waited for never came
```

**Comment by sinuso** [comment] 2024-02-03 10:44
With **-w 5 or 10** and with or without **-d 3** it seems to work on **windows**.
In Linux **without a graphical environment** it seems that it still does not work (I do not have a machine with Linux + graphical environment)


**Result on Linux**

```
test@localhost:~$ renfe-cli -f Barc -t Mad -w 10
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-03
Searching timetable for date: 2024-2-03
loading headless chrome browser
thread '<unnamed>' panicked at src/timetable.rs:86:6:
called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/test/.local/bin/renfe-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: There are no available ports between 8000 and 9000 for debugging
```

**Result on Windows:**

```
C:\Users\Test> renfe-cli -f Barc -t Mad -w 10
Loading stations from Renfe web
Provided input 'Barc' station matches with 'Barcelona (ALL) '...continue
Provided input 'Mad' station matches with 'Madrid (ALL) '...continue
Today is: 2024-2-03
Searching timetable for date: 2024-2-03
loading headless chrome browser
navigating to renfe timetable search page
waiting for search page
adding origin station
adding destination station
adding day
adding month
adding year
searching timetable
got timetable page
wait for timetable iframe
loading timetable
=========================TIMETABLE=========================
Train        |   Departure  |   Arrival    | Duration    
-----------------------------------------------------------
AVE          |    05.50     |    09.10     | 3 h. 20 min.
-----------------------------------------------------------
AVLO         |    06.35     |    09.20     | 2 h. 45 min.
-----------------------------------------------------------
AVE          |    08.00     |    11.12     | 3 h. 12 min.
-----------------------------------------------------------
AVE          |    08.25     |    10.55     | 2 h. 30 min.
-----------------------------------------------------------
REG.EXP.     |    08.43     |    18.09     | 9 h. 26 min.
-----------------------------------------------------------
AVE          |    09.00     |    11.45     | 2 h. 45 min.
-----------------------------------------------------------
AVLO         |    10.00     |    13.17     | 3 h. 17 min.
-----------------------------------------------------------
AVE          |    11.00     |    13.45     | 2 h. 45 min.
-----------------------------------------------------------
AVE          |    12.00     |    15.12     | 3 h. 12 min.
-----------------------------------------------------------
AVE INT      |    12.50     |    15.45     | 2 h. 55 min.
-----------------------------------------------------------
AVE          |    14.00     |    17.12     | 3 h. 12 min.
-----------------------------------------------------------
AVLO         |    15.00     |    17.45     | 2 h. 45 min.
-----------------------------------------------------------
AVE          |    16.00     |    19.12     | 3 h. 12 min.
-----------------------------------------------------------
AVE          |    17.00     |    19.45     | 2 h. 45 min.
-----------------------------------------------------------
AVE          |    17.25     |    19.55     | 2 h. 30 min.
-----------------------------------------------------------
AVE          |    18.00     |    21.12     | 3 h. 12 min.
-----------------------------------------------------------
AVE          |    18.40     |    21.45     | 3 h. 5 min. 
-----------------------------------------------------------
AVE          |    20.00     |    23.12     | 3 h. 12 min.
-----------------------------------------------------------
AVLO         |    21.00     |    23.45     | 2 h. 45 min.
===========================================================
```

**Comment by gerardcl** [comment] 2024-02-03 10:51
Hi @sinuso , that looks good then! 
You are the first windows user that fully validates it is working with a real environment! thanks for that!
Regarding linux without X, that is expected as the tool requires a headless chrome for its purpose. 
Let me know if you are happy with the current result with windows, and if you need to have this working in linux then you also need a basic X (e.g. a desktop setup) environment to make that work. Feel free to provide a README.md update with such use case if you will!
In any case, let me know if we can close this issue.
Gràcies!!!

**Comment by sinuso** [comment] 2024-02-03 11:13
> Hi @sinuso , that looks good then! You are the first windows user that fully validates it is working with a real environment! thanks for that! Regarding linux without X, that is expected as the tool requires a headless chrome for its purpose. Let me know if you are happy with the current result with windows, and if you need to have this working in linux then you also need a basic X (e.g. a desktop setup) environment to make that work. Feel free to provide a README.md update with such use case if you will! In any case, let me know if we can close this issue. Gràcies!!!

Hi @gerardcl, Is it possible to integrate into the application the capability to check if Linux has X installed? In case X is not available, could we use curl or another terminal browser?

It would be fantastic and extremely useful to be able to use the application on any Linux compatible device, be it a computer, Raspberry Pi, Arduino, a watch, phones, refrigerators, and more xD

I am delighted with the application and am interested in continuing to contribute to the best of my abilities. In the event that the application can operate independently of a graphical environment, I intend to develop an API that allows queries to be made from other applications.

**Comment by gerardcl** [comment] 2024-02-03 11:21
hello @sinuso , 

That would be really cool, the problem is that I have not been able to interact with the renfe website without the need of a headless browser, which indeed fully acts as a real user interacting with the website to later parse the final html result. 

There is no API interaction with renfe web at all in regards to get the timetables.

On the other side, I was able to do that with the [rodalies-cli](https://github.com/gerardcl/rodalies-cli), since the rodalies website is way better implemented.

Maybe with rodalies you are happier? 

In any case, feel free to figure out if there is indeed a chance to avoid using a headless browser for the renfe CLI, so far I wasn't able without too much hacking...renfe website is really nuts...I have never seen something like this...

**Comment by sinuso** [comment] 2024-02-03 11:55
I'll look to see if there is a compatible browser, maybe Lynx?
I don't know the link to make the queries.

[rodalies-cli](https://github.com/gerardcl/rodalies-cli) would be great, for now the rodalies ones are the ones that interest me the most.
I tried a few days ago but I have errors because of "libcrypto.so.3"

**Comment by gerardcl** [comment] 2024-02-03 12:06
cool! then let's focus on rodalies-cli! if you did install/use the binary directly provided in the readme then maybe try install the CLI via cargo, check [docs](https://github.com/gerardcl/rodalies-cli?tab=readme-ov-file#cargo-install)

**Comment by sinuso** [comment] 2024-02-03 12:57
@gerardcl, via cargo works perfect :D

**Comment by gerardcl** [comment] 2024-02-03 13:05
I will then close this issue as you are happy so far! 
Bon cap de setmana!

**Closed by gerardcl** 2024-02-03 13:05 UTC
Labels: bug

**Comment by sinuso** [comment] 2024-02-03 18:14
@gerardcl, Would it be a big smoke to use an AI to make queries since an API is not available?

I'm trying Phind and getting some interesting results.

```
╰─>Quins horaris de tren de rodalies hi ha de Sants a Girona per avui?
╭────────────────────────────────────────────── AI Response ───────────────────────────────────────────────╮
│ SEARCH{"query": "horaris tren de rodalies de Sants a Girona avui"}web_results:                           │
│   Segons la informació disponible, els horaris de tren de                                                │
│    rodalies de Sants a Girona avui són els següents:                                                     │
│  • Salida: 10:46, arribada: 12:05 (durada: 1h 19min, directe)                                            │
│  • Salida: 11:45, arribada: 12:23 (durada: 38min, directe)                                               │
│  • Salida: 11:46, arribada: 13:08 (durada: 1h 22min, directe)                                            │
│  • Salida: 12:16, arribada: 13:47 (durada: 1h 31min, directe)                                            │
│  • Salida: 13:50, arribada: 14:29 (durada: 39min, directe)                                               │
│  • Salida: 14:50, arribada: 15:28 (durada: 38min, directe)                                               │
│  • Salida: 15:34, arribada: 16:13 (durada: 39min, directe)                                               │
│  • Salida: 16:05, arrivada: 16:44 (durada: 39min, directe)                                               │
│  • Salida: 16:30, arribada: 17:08 (durada: 38min, directe)                                               │
│  • Salida: 16:46, arrivada: 18:05 (durada: 1h 19min, directe)                                            │
│ El primer tren surt a les 05:56 i l'últim tren surt a les 22:56 [16].                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

```
╰─>Quins horaris de tren de AVE hi ha de Barcelona a Madrid avui?
╭────────────────────────────────────────────── AI Response ───────────────────────────────────────────────╮
│ SEARCH{"query": "horaris tren AVE de Barcelona a Madrid avui"}web_results:                               │
│  Segons la informació disponible, els horaris de tren AVE de Barcelona a Madrid avui són els següents:   │
│  • Sortida: 06:10, arribada: 08:40 (durada: 2h 30min)                                                    │
│  • Sortida: 06:30, arribada: 08:50 (durada: 2h 20min)                                                    │
│  • Sortida: 07:00, arribada: 09:10 (durada: 2h 10min)                                                    │
│  • Sortida: 07:20, arribada: 09:30 (durada: 2h 10min)                                                    │
│  • Sortida: 07:30, arribada: 09:50 (durada: 2h 20min)                                                    │
│  • Sortida: 08:00, arribada: 10:10 (durada: 2h 10min)                                                    │
│  • Sortida: 08:20, arribada: 10:30 (durada: 2h 10min)                                                    │
│  • Sortida: 08:30, arribada: 10:50 (durada: 2h 20min)                                                    │
│  • Sortida: 09:00, arribada: 11:10 (durada: 2h 10min)                                                    │
│  • Sortida: 09:30, arribada: 11:30 (durada: 2h 0min)                                                     │
│  • Sortida: 10:30, arribada: 12:50 (durada: 2h 20min)                                                    │
│  • Sortida: 11:30, arribada: 13:50 (durada: 2h 20min)                                                    │
│  • Sortida: 11:40, arribada: 14:00 (durada: 2h 20min)                                                    │
│  • Sortida: 12:30, arribada: 14:30 (durada: 2h 0min)                                                     │
│  • Sortida: 13:30, arribada: 15:50 (durada: 2h 20min)                                                    │
│  • Sortida: 14:00, arribada: 16:10 (durada: 2h 10min)                                                    │
│  • Sortida: 14:30, arribada: 16:30 (durada: 2h 0min)                                                     │
│  • Sortida: 15:00, arribada: 17:20 (durada: 2h 20min)                                                    │
│  • Sortida: 15:30, arribada: 17:40 (durada: 2h 10min)                                                    │
│  • Sortida: 16:00, arribada: 18:10 (durada: 2h 10min)                                                    │
│  • Sortida: 16:30, arribada: 18:50 (durada: 2h 20min)                                                    │
│  • Sortida: 17:00, arribada: 19:20 (durada: 2h 20min)                                                    │
│  • Sortida: 17:30, arribada: 19:40 (durada: 2h 10min)                                                    │
│  • Sortida: 18:00, arribada: 20:10 (durada: 2h 10min)                                                    │
│  • Sortida: 18:30, arribada: 20:30 (durada: 2h 0min)                                                     │
│  • Sortida: 19:00, arribada: 21:10 (durada: 2h 10min)                                                    │
│  • Sortida: 19:30, arribada: 21:30 (durada: 2h 0min)                                                     │
│  • Sortida: 20:00, arribada: 22:10 (durada: 2h 10min)                                                    │
│  • Sortida: 20:30, arribada: 22:30 (durada: 2h 0min)                                                     │
│  • Sortida: 21:25, arribada: 23:45 (durada: 2h 20min)                                                    │
│                                                                                                          │
│ El primer tren surt a les 06:10 i l'últim tren surt a les 21:25 [19].                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by sinuso** [comment] 2024-02-03 18:15
@gerardcl, Would it be a big smoke to use an AI to make queries since an API is not available?

I'm trying Phind and getting some interesting results.

```
╰─>Quins horaris de tren de rodalies hi ha de Sants a Girona per avui?
╭────────────────────────────────────────────── AI Response ───────────────────────────────────────────────╮
│ SEARCH{"query": "horaris tren de rodalies de Sants a Girona avui"}web_results:                           │
│   Segons la informació disponible, els horaris de tren de                                                │
│    rodalies de Sants a Girona avui són els següents:                                                     │
│  • Salida: 10:46, arribada: 12:05 (durada: 1h 19min, directe)                                            │
│  • Salida: 11:45, arribada: 12:23 (durada: 38min, directe)                                               │
│  • Salida: 11:46, arribada: 13:08 (durada: 1h 22min, directe)                                            │
│  • Salida: 12:16, arribada: 13:47 (durada: 1h 31min, directe)                                            │
│  • Salida: 13:50, arribada: 14:29 (durada: 39min, directe)                                               │
│  • Salida: 14:50, arribada: 15:28 (durada: 38min, directe)                                               │
│  • Salida: 15:34, arribada: 16:13 (durada: 39min, directe)                                               │
│  • Salida: 16:05, arrivada: 16:44 (durada: 39min, directe)                                               │
│  • Salida: 16:30, arribada: 17:08 (durada: 38min, directe)                                               │
│  • Salida: 16:46, arrivada: 18:05 (durada: 1h 19min, directe)                                            │
│ El primer tren surt a les 05:56 i l'últim tren surt a les 22:56 [16].                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

```
╰─>Quins horaris de tren de AVE hi ha de Barcelona a Madrid avui?
╭────────────────────────────────────────────── AI Response ───────────────────────────────────────────────╮
│ SEARCH{"query": "horaris tren AVE de Barcelona a Madrid avui"}web_results:                               │
│  Segons la informació disponible, els horaris de tren AVE de Barcelona a Madrid avui són els següents:   │
│  • Sortida: 06:10, arribada: 08:40 (durada: 2h 30min)                                                    │
│  • Sortida: 06:30, arribada: 08:50 (durada: 2h 20min)                                                    │
│  • Sortida: 07:00, arribada: 09:10 (durada: 2h 10min)                                                    │
│  • Sortida: 07:20, arribada: 09:30 (durada: 2h 10min)                                                    │
│  • Sortida: 07:30, arribada: 09:50 (durada: 2h 20min)                                                    │
│  • Sortida: 08:00, arribada: 10:10 (durada: 2h 10min)                                                    │
│  • Sortida: 08:20, arribada: 10:30 (durada: 2h 10min)                                                    │
│  • Sortida: 08:30, arribada: 10:50 (durada: 2h 20min)                                                    │
│  • Sortida: 09:00, arribada: 11:10 (durada: 2h 10min)                                                    │
│  • Sortida: 09:30, arribada: 11:30 (durada: 2h 0min)                                                     │
│  • Sortida: 10:30, arribada: 12:50 (durada: 2h 20min)                                                    │
│  • Sortida: 11:30, arribada: 13:50 (durada: 2h 20min)                                                    │
│  • Sortida: 11:40, arribada: 14:00 (durada: 2h 20min)                                                    │
│  • Sortida: 12:30, arribada: 14:30 (durada: 2h 0min)                                                     │
│  • Sortida: 13:30, arribada: 15:50 (durada: 2h 20min)                                                    │
│  • Sortida: 14:00, arribada: 16:10 (durada: 2h 10min)                                                    │
│  • Sortida: 14:30, arribada: 16:30 (durada: 2h 0min)                                                     │
│  • Sortida: 15:00, arribada: 17:20 (durada: 2h 20min)                                                    │
│  • Sortida: 15:30, arribada: 17:40 (durada: 2h 10min)                                                    │
│  • Sortida: 16:00, arribada: 18:10 (durada: 2h 10min)                                                    │
│  • Sortida: 16:30, arribada: 18:50 (durada: 2h 20min)                                                    │
│  • Sortida: 17:00, arribada: 19:20 (durada: 2h 20min)                                                    │
│  • Sortida: 17:30, arribada: 19:40 (durada: 2h 10min)                                                    │
│  • Sortida: 18:00, arribada: 20:10 (durada: 2h 10min)                                                    │
│  • Sortida: 18:30, arribada: 20:30 (durada: 2h 0min)                                                     │
│  • Sortida: 19:00, arribada: 21:10 (durada: 2h 10min)                                                    │
│  • Sortida: 19:30, arribada: 21:30 (durada: 2h 0min)                                                     │
│  • Sortida: 20:00, arribada: 22:10 (durada: 2h 10min)                                                    │
│  • Sortida: 20:30, arribada: 22:30 (durada: 2h 0min)                                                     │
│  • Sortida: 21:25, arribada: 23:45 (durada: 2h 20min)                                                    │
│                                                                                                          │
│ El primer tren surt a les 06:10 i l'últim tren surt a les 21:25 [19].                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

Salut i molt bon cap de setmana

**Comment by gerardcl** [comment] 2024-02-03 18:43
hi @sinuso !
In the current scope of the project I would not add a middleware that can't be tested as generatives AI are.
Indeed, I just did a fast check from the current CLIs to compare the results you got and they are not right, which confirms previous statement.
In any case, I find it really interesting and something to explore, but maybe the scope would be to focus first on doing a proper training of such a base model. But, I am not sure if with Phind or any other models out there one can perform a real-time search in the way we require here. I mean, it is not impossible but I believe one would require too much power and might end up being a too over engineered solution.
Happy to hear more about your ideas!
Salut!
